version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app1
      - app2
      - app3
  mysql-db:
    image: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Ragc2806
      MYSQL_DATABASE: mysqlbd
    ports:
      - 33060:3306

  app1:
    container_name: evaluacion1_docker1
    image: robertogalleguillos/evaluacion1_docker
    ports:
      - "8091:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mysqlbd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Ragc2806
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
  app2:
    container_name: evaluacion1_docker2
    image: robertogalleguillos/evaluacion1_docker
    ports:
      - "8092:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mysqlbd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Ragc2806
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db

  app3:
    container_name: evaluacion1_docker3
    image: robertogalleguillos/evaluacion1_docker
    ports:
      - "8093:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mysqlbd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Ragc2806
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db